config:
  project_repos:
    dspace_7:
      repo: 'https://github.com/EOSC-synergy/DSpace_7.git'

sqa_criteria:
  qc_coverage:
    repos:
      dspace_7:
        container: dspace-testing
        commands:
          - mvn -X -f /dspace-testing/pom.xml checkstyle:check

environment:
  GIT_COMMITTER_NAME: Fernando
  GIT_COMMITTER_EMAIL: aguilarf@ifca.unican.es
  LANG: C.UTF-8
  JPL_DOCKERFORCEBUILD: "enabled"

timeout: 600
